spring:
  profiles:
    active: dev
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true #?
  kafka:
    bootstrap-servers: localhost:9092

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

jwt:
  secret: PF0QWCZUrwhimpysmXvy9LAxJCcD6tU1lQvIo+hlBiQ= #Это поле содержит секретный ключ, который используется для подписи JWT токенов
  expiration: 3600000 #Это поле содержит время жизни jwt токена в миллисекундах

logging:
  level:
    org:
      springframework: TRACE
#        security: TRACE