spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
    username: sa
    password: ""
    driver-class-name: org.h2.Driver

logging:
  level:
    repository:
      TicketRepositoryImpl: DEBUG
    root: INFO