spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
#    continue-on-error: true

logging:
  level:
    repository:
      TicketRepositoryImpl: DEBUG
    root: INFO
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE