---
spring:
  profiles:
    active: dev
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      enabled: true
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  kafka:
    bootstrap-servers: localhost:9092

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

jwt:
  secret: PF0QWCZUrwhimpysmXvy9LAxJCcD6tU1lQvIo+hlBiQ=
  expiration: 3600000

logging:
  level:
    org:
      springframework: TRACE
