name: JaCoCo Coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle and Generate Coverage Report
        run: ./gradlew clean build jacocoTestReport
      - name: Update README with Coverage Badge
        uses: yiiu2/action-update-readme-badge@v1.0
        with:
          readme_path: README.md
          known_badge: [![JaCoCo Coverage](https://github.com/CyberXAndrew/transport-ticket-system/actions/workflows/jacoco.yml/badge.svg)](https://github.com/CyberXAndrew/transport-ticket-system/actions/workflows/jacoco.yml)